spring:
  application:
    name: resource-service
  
server:  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}    prefer-ip-address: true  client:    register-with-eureka: true 
    fetch-registry: true    
    service-url:      defaultZone: http://localhost:8761/eureka

           